version: '2'

networks:
  gestao-agro-tech-network:
    name: gestao-agro-tech-network
    driver: bridge

volumes:
  postgres:

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: psql123
      POSTGRES_DB: agrotechdb
      SCHEMA: public
    ports:
      - 6000:5432
    volumes:
      - ./sql-data/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
    #  - /home/renatogroffe/Desenvolvimento/Docker-Compose/PostgreSQL:/var/lib/postgresql/data 
      - ./postgres:/var/lib/postgresql/data
          # copy the sql script to create tables
    networks:
      - gestao-agro-tech-network
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@user.com.br"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - gestao-agro-tech-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - gestao-agro-tech-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - gestao-agro-tech-network

  kafka-topics-creator:
    build:
      context: kafka-topics-creator
      dockerfile: Dockerfile
    container_name: kafka-topics-creator
    depends_on:
      - zookeeper
      - kafka
    environment:
      ZOOKEEPER_HOSTS: zookeeper:2181
      KAFKA_TOPICS: "topico-gestao-agro-tech"
    networks:
      - gestao-agro-tech-network

  gestaoagrotech:
    network_mode: host
    build: .
    ports:
        - 8080:8080
    depends_on:
        - zookeeper
        - kafka
        - kafka-topics-creator
        - postgres
        - pgadmin
    


